### ISSUE TITLE
Shields in UK

### ISSUE THREAD

**Issue by SK53** [ZeLonewolf/openstreetmap-americana#106]
I'm not sure that UK roads truly have shields, but the basic minimum for a reasonably accurate representation is:

* European routes (E-*): these are not signed in the UK and shields are no use for motorists. I'm not sure if the relevant relations are tagged unsigned=yes, and anyway unsigned is probably not supported in OMT
* Motorways should have white lettering on a blue background to the shield. These are pretty common on signposts.
* Trunk roads should have  a yellow lettering on a green background to the shield. Note this conflicts with current E-route rendering.
* Other roads (primary & secondary) should be black letters on a white background. Note virtually all ref on other road classes is a tagging error (these are extremely rarely signed & when they have been the highway authority is not following the guidance) & are best not shown.

A reasonable selection of examples on the [Sabre wiki](https://www.sabre-roads.org.uk/wiki/index.php?title=Direction_Sign).

Note this issue is raised for information, rather than with any expectation that it might be implemented. The only thing which I think is important is the suppression of shields for E-routes, as showing them may affect users' expectations.

**Comment by ZeLonewolf** [comment]
Regarding:
> European routes (E-*): these are not signed in the UK and shields are no use for motorists. I'm not sure if the relevant relations are tagged unsigned=yes, and anyway unsigned is probably not supported in OMT

We have both `ref` and `unsigned_ref` (rather than the barely used `unsigned=ref`) to indicate whether or not a numbered route is signed.  This is how we deal with the situation in the US, where we have both signed and unsigned routes.  This style suppresses shields whenever a `ref` is not present, unless the route is of the type that doesn't have a ref but still has a shield (there are a number of these special cases in the US).

The E route relations that run through the UK are tagged with `ref` and therefore this style displays them as signed.  The EU/UK community should consider this an opportunity to improve the tagging such that unsigned portions of E-road routes are members of relations tagged with `unsigned_ref`.  If this is able to change in the tagging, the E-road shields will disappear from the map on the next update of the underlying vector tiles.

For awareness, the shields displayed by this style are generated solely through route relations and ignore `ref` tagging on ways entirely.  We have been slowly building out shields for mainland Europe as they are displayed on signage and I would consider it in scope to do the same for the UK.

Tasks:

- [ ] Update UK route relations so that unsigned E-roads are members of relations with `unsigned_ref` tagging
- [ ] Add shields for UK roads that are mapped with route relations

- [ ]

**Comment by ZeLonewolf** [comment]
What would be helpful to moving forward on the UK-specific signs is some kind of indications of what color schemes are used for different routes and how they are tagged:

![image](https://user-images.githubusercontent.com/3254090/151380164-527555c0-255e-4b8c-955d-197bd8e7dbf1.png)

**Comment by zekefarwell** [comment]
> in the UK highway refs will almost always be on the way and not on a relation

This style uses route relations for highway shields.  No route `ref` on route relation = no shield.  The only exceptions to this are for special cases like the [New York Thruway](https://en.wikipedia.org/wiki/New_York_State_Thruway) where a route legitimately has no number or code on it's shield.

**Comment by 1ec5** [comment]
> What would be helpful to moving forward on the UK-specific signs is some kind of indications of what color schemes are used for different routes and how they are tagged:

[This chapter of the _Traffic Signs Manual_](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/782725/traffic-signs-manual-chapter-07.pdf#page=19) explains the color-coding system on UK directional signs. If I’m interpreting this document correctly, the background and patch colors seen in https://github.com/ZeLonewolf/openstreetmap-americana/issues/106#issuecomment-1023276656 indicate road classifications but aren’t integral parts of a route marker as in other countries:

* The indication for the A505 to Letchworth has a white background because it follows a non-primary road (classified as `secondary` in OSM).
* The indication for the A505 to Royston and Baldock has a green background because it follows a primary road (classified as `trunk` in OSM).
* The gore sign’s blue patch for A505 looks like it’s just meant to match the sign background, as if to cover up something that was there before. Either that or it’s splitting the difference between the white and green backgrounds on the subsequent lane advance direction sign.

openstreetmap-carto draws way `ref`s as capsules that match the color of the associated roadway. If my interpretation above is correct, that treatment makes sense in the UK, because the background color is part of the identity of the roadway rather than of any route it carries. It’s a very different way of doing things than in MUTCD countries or the various European countries this renderer currently supports.

**Comment by Mashin6** [comment]
I used one rogue relation to make this 
![image](https://user-images.githubusercontent.com/5265707/152656437-77ed0293-2db5-4bf2-bfe9-236e44739834.png)

**Comment by SK53** [comment]
> 
>     * The indication for the A505 to Letchworth has a white background because it follows a non-primary road ([classified as `secondary` in OSM](https://www.openstreetmap.org/way/262396323)).
> 
No, the OSM standard is A-roads are either 'trunk' (i.e., with yellow on green signage) or 'primary'. So official "non-primary A-roads" are still highway=primary in OSM.  Only B-roads receive a highway=secondary tag. 

Unfortunately official terminology has changed over the years so that whereas there were many trunk roads in the past (on old maps they were denoted by "(T)" after the A###, with remaining A-roads being primary. Now the old trunk network is called primary with new trunks being a small subset of roads which are maintained by a national agency. However, current national classification is not relevant to OSM tagging: which is based more on things easily observed on the ground (signage colour & ref). (Not that this prevents someone deciding now and then that we should be mapping the latest set of official documents).

If you look at OSGB Landranger mapping they colour code roads in a similar way to OSM ([example of area](https://www.cucaera.co.uk/grp/?refs=ST46&map=ordnance&vcs=true&graticule=true&nsgrids=false&zoom=12&lat=51.351456813208465&lon=-2.857475280761719&distinct=false&bedrock=false&superficial=false&sketches=) of Somerset above on Cucaera's site). This would have been the original target of Blackadder's first iteration of "map features".

**Comment by ZeLonewolf** [comment]
> Unfortunately official terminology has changed over the years so that whereas there were many trunk roads in the past (on old maps they were denoted by "(T)" after the A###, with remaining A-roads being primary. Now the old trunk network is called primary with new trunks being a small subset of roads which are maintained by a national agency. However, current national classification is not relevant to OSM tagging: which is based more on things easily observed on the ground

Uh... my head is spinning here 🤪

Ultimately what we need is a mapping between `network` value and sign appearance.

**Comment by ZeLonewolf** [comment]
I suspect that it does not make sense to attempt to render shields in the UK based on how the roads are named and signed. I would consider the various A, B, C, etc routes to really be road names in the same way that "5th Avenue" would be in North America.  I would consider the fact that unwanted E-route shields are currently rendered to be a tagging error. Also, there does not seem to be strong consistency of sign coloring along a route, but rather indicate road classifications, which are a related but separate concept. Additionally, it does not appear that there is any appetite in the UK for the mapping of route relations, especially since routes are not a concept in the same way in the UK as they are in North America.

I would be open to rendering the blue [Vienna Convention motorway symbology](https://en.wikipedia.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals) as so nicely demonstrated by @Mashin6, should the motorways become mapped in route relations.

For these reasons, I propose that this ticket be closed as wontfix.

**Comment by ZeLonewolf** [comment]
Gaps in a route relation are no problem for the renderer, from a technical standpoint.

This example I think is the first time I've been aware of an A road route relation in the UK.

Would it be correct for such a route to be rendered with a shield like this?
![image](https://user-images.githubusercontent.com/3254090/209184723-e3f55cc2-901d-468c-87d9-3db9aa8bdf13.png)

Or does that coloring change in places based on other factors?

Would the GB community be open to adding a network value to route relations like that one?  I would suggest `GB:A`.

**Comment by ZeLonewolf** [comment]
Also of note, Google Maps does not render shields in the UK except for motorways:

![image](https://user-images.githubusercontent.com/3254090/209185906-e593b533-db08-4358-8d72-98b1f78bb186.png)

**Comment by ZeLonewolf** [comment]
Different colorings for the same route on an overhead gantry:

![image](https://user-images.githubusercontent.com/3254090/209186267-99277232-64e9-4200-9b0b-cbcc2e67d060.png)

**Comment by trigpoint** [comment]
It changes depending on the highway classification. That sign is correct for the highway=trunk sections however the highway=primary sections has white signs with black lettering.

There are two types of A road.

**Comment by trigpoint** [comment]
> Different colorings for the same route on an overhead gantry:
> 
> ![image](https://user-images.githubusercontent.com/3254090/209186267-99277232-64e9-4200-9b0b-cbcc2e67d060.png)

That is the end of an A5 section, there is then a gap indicated by parenthesis as the directions to. In this case different routes for different classifications of traffic to follow to rejoin.

Learners, bicycles, agricultural vehicles, tracked vehicles are prohibited on motorways.


Where the A5 begins again there are white signs.

**Comment by ZeLonewolf** [comment]
Thanks.  I too was hunting for those examples :)
![image](https://user-images.githubusercontent.com/3254090/209188214-ea57818a-3915-46b5-84d1-c051729532ee.png)

I took a look at the data and it does seem like we have something encoded that would work for this:
![image](https://user-images.githubusercontent.com/3254090/209188866-c91e596d-9a7c-4da3-a78e-f7198c1692bd.png)

It appears that OpenMapTiles may need an update to fix its network encoding to allow highway classification to override its pseudo-network generation.

**Comment by trigpoint** [comment]
That could work.

Although road route relations are not especially common in the UK. I would expect them to be on the first 99, rather than on 3 or 4 digit A roads or B roads

**Comment by ZeLonewolf** [comment]
The code for this feature is implemented as of #696, however, results will not be visible in the map until the next version of OpenMapTiles and planetiler is released.
