### ISSUE TITLE
Support variable-width rectangular & oval signs

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#117]
For cases where signs are plain squares or rectangles, we've drawn white squares with black borders.  This has covered states like CT/RI/MA/ME which use state highway shields that look similar.  However, in most cases, 3+ digit signs are drawn as rectangles:
![image](https://user-images.githubusercontent.com/3254090/151674898-e9590362-30b7-4e0b-be61-7c04a65e1304.png)

while shorter route numbers are drawn as squares:
<img src="https://user-images.githubusercontent.com/3254090/151674954-83da635f-2968-45f6-8e0b-6836d45c4159.png" width=100>

Thus, we should make these generically-drawn signs variable-width, perhaps up to a 3:2 or 2:1 ratio rather than squeezing the text into a square.

**Comment by 1ec5** [comment]
Same goes for circular shields, which don’t fit longer refs very well. In fact, Kentucky has many four-digit-long refs, but they use rounded rectangles instead of ellipses.

**Comment by ZeLonewolf** [comment]
Though it's not quite a rounded rectangle, how would we feel about using ellipses as the generalized expansion of round shields?

![image](https://user-images.githubusercontent.com/3254090/151701936-d8915ab0-86a0-4f83-9a10-425da18979cc.png)

**Comment by zekefarwell** [comment]
The ellipses certainly look better than shrinking long refs into circles.
<img width="295" alt="Screen Shot 2022-01-30 at 1 10 58 PM" src="https://user-images.githubusercontent.com/281482/151711866-1f5af176-bb1f-4a48-848f-7a859d6c7f86.png">

The [real world elliptical shields](https://commons.wikimedia.org/wiki/Category:Elliptical_route_shields) seem rounder to me though.  Maybe they don't end up being as wide due to narrow text with 3 digits.
![image](https://user-images.githubusercontent.com/281482/151711936-d7dfffe7-c46b-4692-89a9-3cc022c70d75.png)

At the small size we're displaying these shields, I think rounded rectangles (elongated circles) will probably look better.  It may not make too much difference for a 3 digit ref, but I think it will look quite a bit better for longer refs.
![image](https://user-images.githubusercontent.com/281482/151711995-3eb6212c-1a33-46e4-8239-2f88a609e868.png)

If we were trying to be 100% real wold accurate, we'd use ellipses for some states and rounded rectangles for others.  That seems overly detailed to me though.  I'm in favor of using the same shape for all "ovalish" shields.

**Comment by ZeLonewolf** [comment]
Since we have the ellipses implemented, is there any reason not to use the ellipse on a real-world shield that's elliptical?  Then we can just add rounded rectangles for signs that should be rounded rectangles.  We can also dump all the basic European shields from the sprite sheet in favor of drawn rounded rectangles sized to fit.

**Comment by zekefarwell** [comment]
That is a good point.  Rounded rectangles can have widely varying corner radii.  Our generic rectangle shield would probably look better as a rounded rectangle with a very small corner radius to match the real world signs.  A yes that would allow us to get rid of the majority of the european shields too.  The "elongated circle shields are a very specific type of rounded rectangle with a max-out corner radius.  I think this elongated circle looks better on maps than ellipses.  The ellipses end up getting very pointy looking as they get wider.

Basically I think these shapes
<img width="292" alt="Screen Shot 2022-01-30 at 3 20 24 PM" src="https://user-images.githubusercontent.com/281482/151716222-9ceb04d9-8f62-4ba4-b2a8-8bf4e87a12bc.png">

look better than these shapes
<img width="403" alt="Screen Shot 2022-01-30 at 3 21 10 PM" src="https://user-images.githubusercontent.com/281482/151716246-16ab43f5-a0ac-485a-9995-2b9280acc72e.png">

To me, an elongated circle is close enough to an ellipse that it seems fine to use instead even in states where the real world shields are actually elliptical.  If other folks are excited about real ellipses, though, I have no problem with that.

**Comment by 1ec5** [comment]
Either would be equally recognizable to a Kentuckian. Both shapes are quite common on maps of Kentucky. (I grew up just across the border in Ohio, so I’m used to seeing both on TV news maps.) For a state that uses ellipses on signs, such as Mississippi, I don’t know if the elongated circle would look as familiar, but at worst it would look like a stylistic choice with plenty of precedent.

The elongated circle would be one solution to West Virginia’s fractional county road shields. It would be trivial to stick a six-character-long `ref=340/14` in there as is, although a distinct stacked image would be more accurate.

**Comment by ZeLonewolf** [comment]
Stacked text derived from a slash-separated ref is already needed for #85.  So if we implement that, it seems like it could be feasible to do the same for WV.  For the WV case we could perhaps make the elongated circle go vertically instead of horizontally, with a fixed width basis.
