### ISSUE TITLE
Extract loadShields objects into JSON

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#118]
The `loadShields()` function in shield_defs.js will get unwieldy as we continue to add support for more networks. I think most of the objects in this function could be converted to JSON without losing expressiveness; then, the function could load the data and transform it into the data structure needed by its callers. A JSON file will be less intimidating for non-programmers to contribute to and possibly be easier to refactor in the future.

**Comment by ZeLonewolf** [comment]
Sounds good to me.  We would have to convert the function references into an enum scheme to make that work, I think?

**Comment by zekefarwell** [comment]
I agree the the `loadShields()` function will get unwieldy as it grows (at over 500 lines long it's arguably already there).  Extracting the `shields` data structure out of that function definitely makes sense, but I'm not sure it needs to be JSON.  I think I'd prefer a standard object declaration in JS.  More flexible syntax, possible to use variables, etc.  It seems unlikely to me that non-programmer would really find JSON more approachable than a JS object declaration that looks basically the same.  It's been a while since I was a non-programmer though, so hard to put myself in those shoes.

**Comment by ZeLonewolf** [comment]
The point about using variables is a good one.  There's a bunch of duplication that we're avoiding by re-using common shapes.  The NJ counties alone would be a significant inflation in size if we produce a JSON version of the shield definitions.

**Comment by 1ec5** [comment]
A literal translation to JSON would result in redundancy, but I’m pretty confident we could figure out ways around that. In particular, we should rename heavily reused icons like shield40_us_county to be more generic, as suggested in https://github.com/ZeLonewolf/openstreetmap-americana/pull/113#issuecomment-1025002165.
