### ISSUE TITLE
Ref values pre-processing

### ISSUE THREAD

**Issue by Mashin6** [ZeLonewolf/openstreetmap-americana#141]
Some countries have `ref` values that include additional characters such as `A1`. But in real life traffic signs only show the number: `1`.
![image](https://user-images.githubusercontent.com/5265707/152661800-57ca2b39-2619-4806-b7b7-e4e6fa8317fc.png)
vs
![image](https://user-images.githubusercontent.com/5265707/152661870-f4ad0383-ba9d-4de7-8c4e-fc5a04bbdd4c.png)

The biggest problems this is causing is in Romanian trunk roads shields (#99), but this issue is present in other countries as well:
Germany, Switzerland, Italy, Czechia.

A possibility would be to add a function that would strip of letter characters from refs in certain countries.

**Comment by 1ec5** [comment]
In #119, I implemented a `refsByWayName` lookup table specified as part of an individual shield definition object. It could be generalized into a function: these European shield definitions would implement the function by deleting the letter, while the Kentucky parkway shield definition could look up the value based on the `ref` (assuming we don’t find a more data-driven way to implement that shield definition).

**Comment by ZeLonewolf** [comment]
I think ref pre-processing is something we should do under only extremely exceptional circumstances, if even at all.  It sounds like there is a relatively small list of countries that have tagged their highway route relations in a way that's different from the rest of the planet.  If that's the case, I'm fairly comfortable rendering them wrongly and suggesting that they might change the tagging to be more consistent with the global trend.

I noticed Italy in that list, and Italy does have the prefix values in their signs so I think in that case the ref prefix should actually be there and be rendered.

**Comment by 1ec5** [comment]
I think a transformation mechanism would be useful anyways. Thinking ahead to when we add the full complement of Texas shields, we’ll probably want to display most of the networks’ shields as something like `[FM 1234]` and `[PA 1502]`, which would require prepending something to the bare `ref` that ordinarily shouldn’t be there in the data.

**Comment by ZeLonewolf** [comment]
> Thinking ahead to when we add the full complement of Texas shields, we’ll probably want to display most of the networks’ shields as something like `[FM 1234]` and `[PA 1502]`, which would require prepending something to the bare `ref` that ordinarily shouldn’t be there in the data.

This could also be accomplished by making the prefix part of the shield artwork.

**Comment by 1ec5** [comment]
The letters would have to be counterbalanced with whitespace on the other side of the image, which would shift the shield away from the roadway in many cases.

**Comment by ZeLonewolf** [comment]
The other thought I had for cases like the Texas route was to make the prefix a modifier, so it would render as text above, which could be done right in the shield definitions.

**Comment by 1ec5** [comment]
> The other thought I had for cases like the Texas route was to make the prefix a modifier, so it would render as text above, which could be done right in the shield definitions.

#177 does this for Ohio township routes, and it seems like Texas routes would fall into the same boat.

**Comment by 1ec5** [comment]
I think there should be a transformation step, but only one that adds text, not one that removes it. This is a common need for route networks that, for whatever reason, only use one text size on their shields. For example, many Asian route networks are signposted with distinctive shields that put a letter immediately before the route number in the same typeface. For example, the Asian Highway network (#122) is [signposted](https://commons.wikimedia.org/wiki/Category:Route_shields_of_the_Asian_Highway_Network) with “AH ###” in most countries.

It would be incorrect to put `AH` directly in the `ref` of each route relation, because that would prevent other data consumers from being able to synthesize a name like “Asian Highway 1”. Unlike the British “M1 motorway”, it would be incorrect to redundantly say “Asian Highway AH1”. In my opinion, it isn’t a big deal for Americana to concatenate a prefix onto a `ref`, but it would be quite unfortunate if other data consumers have to parse `ref` on relations in the same manner that legacy data consumers had to parse `ref` on ways.

To keep the preprocessing from being misused for more complex transformations, a shield definition could specify a ref format, similar to the [road number formatter](https://www.wikidata.org/wiki/Property:P8498) property on Wikidata.

**Comment by JannikGM** [comment]
> A possibility would be to add a function that would strip of letter characters from refs in certain countries.

Yes. If you know that this is a specific road (like an Autobahn starting with "A ") then you can [use a `slice` expression in mapbox](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice). However, [it's not supported in maplibre-native and mapbox-native yet](https://github.com/maplibre/maplibre-gl-native/issues/264), so this would only work on the web.

To figure out if this even an Autobahn in the first place, we'd first have to solve https://github.com/openmaptiles/openmaptiles/discussions/1369 (or fill out all the tags in OSM).

**Comment by zekefarwell** [comment]
@JannikGM, see relevant discussion here https://github.com/ZeLonewolf/openstreetmap-americana/discussions/149

**Comment by claudiush** [comment]
Here's another national freeway shield that might require preprocessing: Iranian shields contain the reference number on top right in Eastern Arabic Numerals and bottom right in Western Arabic Numerals (Example shield for Freeway 2: https://commons.wikimedia.org/wiki/File:Azadrah2-IR.png ). 
OSM relations contain Western Arabic Numerals in the ref tag and sometimes the Eastern Arabic as ref:fa. (Example relation: https://www.openstreetmap.org/way/320844736 - Example way with ref:fa: https://www.openstreetmap.org/way/320844736 )

**Comment by zekefarwell** [comment]
Displaying the Persian numerals is probably out of scope for the Americana project.  It looks like a the western Arabic numerals in a appropriately colored rectangle would work just fine for these routes if we were to add support for them.  For a renderer that did want to display the Persian numerals, it looks like reading for the `ref:fa` tag would be the way to do that.

**Comment by ZeLonewolf** [comment]
Internationalization of non-latin script numbers is certainly an interesting idea.  If anything, it would make more sense to put the whole map in a latin script or a different script, and have that translation be done in the javascript side.  I agree with @zekefarwell that we probably don't want to show both simultaneously.  Feel free to open a new issue for script toggling, but it's something that requires code changes and a fair amount of thought.

**Comment by 1ec5** [comment]
It is possible, [with a glorious hack](https://stackoverflow.com/a/55366435/4585461), to parse a non-European number as long as the input and output languages are known.

/ref openstreetmap/iD#8769

**Comment by Blijbol** [comment]
The Netherlands also needs ref pre-processing for correct rendering. When written in text, no space is written between the letter and number (e.g. one would write "The A44 was congested.", and hence also the tagging as ref=A44). However, when displayed on signs, there is subtle spacing between the letter (A) and number (44) to enhance readability:

![Nederlands_verkeersbord_K1](https://user-images.githubusercontent.com/489845/167709940-1bc794a8-fba8-4465-b453-a89c2f199da7.svg)

**Comment by ZeLonewolf** [comment]
> The Netherlands also needs ref pre-processing for correct rendering. When written in text, no space is written between the letter and number (e.g. one would write "The A44 was congested.", and hence also the tagging as ref=A44). However, when displayed on signs, there is subtle spacing between the letter (A) and number (44) to enhance readability:

That's a very subtle difference.  In general, the highway shields we've drawn on the map at icon size are representative but not perfect replicas of the shields shown in reality.  Of course, since most European highways shields are boring shapes like rectangles or hexagons, they usually end up being very close to reality!  I'm not sure that this tiny gap is a big enough deal that we _need_ to build in the custom code that would insert a few pixels of space there.  I suspect that most Dutch users would recognize the white-on-red shields with or without the additional kerning space.

**Comment by Blijbol** [comment]
It is of course still recognisable without the space, but the space does improve readability of the map, just like it improves readability of road signs.

**Comment by bgo-eiu** [comment]
Re: Persian numerals, it is notable that Iran is surrounded by countries that don't use them. Not displaying the numerals would impede recognizability of the shield by removing part of what makes them distinct. I don't know if anyone is looking at Americana while crossing the Pakistan - Iran border yet, but since Pakistan uses "European" Arabic numerals on signs you would see a difference on the ground.

If you didn't understand either numeric system or language involved, you would still be able to recognize the symbols/glyphs if they matched. I would add for English speakers in particular though, Persian/Arabic numerals don't actually differ that much from 1234... etc. if you look at it for an extra moment you can probably tell exactly what number it is without issues.

**Comment by 1ec5** [comment]
This style currently shows labels in English for usability. We aren’t making users figure out Cyrillic text despite significant orthographic similarity to Latin. It is possible to figure out which European numeral corresponds to which Arabic numeral, but not everyone will intuit that it is a comparable numeral system in the first place.

Ideally it would be the responsibility of OpenMapTiles to offer the ref in two writing systems, just as with `name:latín`. (This would be sensible especially for the UAE, which includes both Latin and Arabic ref prefixes on its shields.) By ensuring we have the data in both writing systems, we’ll have the flexibility to switch between them based on a user language preference.

**Comment by 1ec5** [comment]
As of #193, we’re also showing some Chinese characters in shields that would ideally be replaced by letter suffixes such as A/B/C or N/S/E/W.

**Comment by bgo-eiu** [comment]
Hmm I guess I'm sort of confused about what people would find useful here. I think of route numbers as symbols and to that end I would think

**Comment by ZeLonewolf** [comment]
Support for adding pseudo refs from way names (Kentucky parkways) was added in #119 and support for stacked refs (Italy, et al.) is documented in #366.  Supporting network identifiers that are not posted on shield definitions is not planned, and should be regarded as a tagging error.
