### ISSUE TITLE
Assign highway shield based on ref value

### ISSUE THREAD

**Issue by Mashin6** [ZeLonewolf/openstreetmap-americana#142]
In some communities they have chosen to group all their roads under a single `network` value with an assumption that certain letter codes in `ref` would be sufficient to split them apart. An option would be to define shield graphics not only by an exact match of `network`, but also by an additional regex match in `ref` values.
This will have to be carefully crafted around ref preprocessing #141 in case it will be implemented.

Countries that are affected:
Hungary [#69](https://github.com/ZeLonewolf/openstreetmap-americana/issues/69#issuecomment-1013750719)
Portugal
Bulgaria
North Macedonia

**Comment by 1ec5** [comment]
> In some communities they have chosen to group all their roads under a single network value with an assumption that certain letter codes in ref would be sufficient to split them apart.

As I understand it, the main reason for migrating to route relations with distinct `network`s was to keep data consumers from having to sniff out alphabetic codes the way they had been with `ref`s on ways. It would be helpful to know the reasoning behind replicating the same unstructured format on relation `ref`s. Maybe these communities could be convinced to make their route relation tagging more structured.

**Comment by Mashin6** [comment]
With Hungarian community [that didn't work out.](https://github.com/Mashin6/detect-mutations)

There is also an option of not doing anything about it. It's all just a suggestion.

**Comment by ZeLonewolf** [comment]
My impression is that the countries listed have grouped together multiple de facto highway networks under a common network value, and that this is properly solved with a tagging solution rather than a rendering one.  Thus, I agree with closing this issue upon merge of #355, as the ask here "assign highway shield based on ref value" will be resolved.  I don't think we should make special code for the case of insufficiently structured `network` tagging schemes.
