### ISSUE TITLE
Implement language switching in URL querystring

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#20]
Depends on #19

A key feature of vector tiles is the ability to switch languages for name labels.  OpenMapTiles provides `name:xx` tags wherever a `name` tag is available.  Proposed is that the following parameters can be parsed from the querystring:

*`lang0=xx` - use `name:xx` tag for name features
*`langN=xx` - use `name:xx` as a fallback language if the `lang0` language is not available.  N is numbered from 1 and counting up

If none of the specified languages or fallback languages are set, this will default to one of the standard name values (one of `name`, `name_int`, or `name_latin`).

In javascript, a JSON fragment will need to be generated which creates a case statement to switch the specified language names, which is then inserted into the appropriate locations in the style JSON variables.

**Comment by ZeLonewolf** [comment]
The following library may be of use:
https://github.com/klokantech/openmaptiles-language

**Comment by 1ec5** [comment]
> The following library may be of use: https://github.com/klokantech/openmaptiles-language

This script predates expressions and uses the deprecated string interpolation syntax, so it’s incompatible with this project. It also isn’t distributed as an NPM package. There is [a compatible Mapbox GL JS library](https://github.com/mapbox/mapbox-gl-language/) for localizing labels. However, I don’t think a library is necessary at all. Unlike most styles that are distributed in static JSON format, Americana is built at runtime in JavaScript, giving us the ability to inject environment variables like the language as we build each layer. #578 implements this approach without needing to hard-code a single `name:*` field.

#578 relies on user preferences, but I agree that it would be handy to be able to set the language inside the URL. There are two typical approaches to implementing a URL-based language switch:

* A `?language=` query parameter would be ideal. I think GitHub Pages supports query parameters just fine, but when running `npm start`, appending any query parameter currently results in a 404. We would need nativew/serve#8 to land before taking this approach.
* A `#language=` hash “parameter” is a common alternative. It has the benefit of implying that the user can change the language without reloading the page, which would be feasible: https://github.com/ZeLonewolf/openstreetmap-americana/pull/578#discussion_r1032848256. Unfortunately, we’re currently using the basic hash y/x/z hash format, which leaves no room for additional parameters. The fix is simply to set `hash` to the string `map` here: https://github.com/ZeLonewolf/openstreetmap-americana/blob/0ff8c2434ab61496b2548687ed1cc7436179bfd3/src/americana.js#L286 This would be consistent with the rest of the OSM ecosystem, including osm.org and iD. However, this would break all existing links to specific locations in Americana unless we add a compatibility shim.

**Comment by jleedev** [comment]
Can also switch to esbuild's `serve` api.
