### ISSUE TITLE
Alberta highway shields

### ISSUE THREAD

**Issue by TagaSanPedroAko** [ZeLonewolf/openstreetmap-americana#218]
Alberta provincial highways numbers should be rendered with these shields:

- Highways 1 and 16 (network=CA:transcanada): Maple leaf outline shield (would desire a simple maple leaf without green rectangle, if to take in account the slightly different design used by Newfoundland and Labrador, a green shield with a maple leaf, as against most provinces that use a green rectangle with the leaf)
- 1-216 series highways excluding Highways 1 and 16 (network=CA:AB:primary): squared-off white shield. Highways 3 (Crowsnest Highway), 35 (Mackenzie Highway) and 88 (officially Bicentennial Highway) use standard Alberta highway shield, but with extra elements that are under Crown copyright; most maps would defer to using the simple shield
- 500-986 series highway (network=CA:AB:secondary): oblong

**Comment by TagaSanPedroAko** [comment]
Reference for standard highway shield shape: Alberta Highway Guide and Information Sign Manual (https://open.alberta.ca/dataset/d2890998-9341-4c3b-bebb-96e5103eb57a/resource/f823c311-b7ba-40db-9bb2-05339e83c038/download/guide-info.pdf), Section A4.4

**Comment by TagaSanPedroAko** [comment]
@1ec5 @ZeLonewolf Demos with the desired shields?

**Comment by 1ec5** [comment]
It’s high time we embark on support for Canada’s route shields, so thanks for providing us with this information!

I think we’d definitely prefer the “guide sign route number shield” designs per [section A4.4.1](https://open.alberta.ca/dataset/d2890998-9341-4c3b-bebb-96e5103eb57a/resource/f823c311-b7ba-40db-9bb2-05339e83c038/download/guide-info.pdf#page=47), as well as just the maple leaf outline (with the banner below it?) for the Trans-Canada Highway. That’s the same approach we’ve been taking in various U.S. states for simplicity.

The [special trailblazers](https://open.alberta.ca/dataset/d2890998-9341-4c3b-bebb-96e5103eb57a/resource/f823c311-b7ba-40db-9bb2-05339e83c038/download/guide-info.pdf#page=51) are intimidating (and copyrighted), but it sounds like they’re redundant to standard numbered shields, correct? Could we gain any usability by showing a small, simplified replica of one of these trailblazers?

Slightly off-topic for this request about Alberta, but since you’re asking for TCH support, what should we do with [`network=CA:transcanada:namedRoute`](https://www.openstreetmap.org/relation/11074496) routes? Do they represent roads that we should label with an unnumbered TCH shield after the normal numbered shield?

> Demos with the desired shields?

Sorry, can you clarify what this question is about?

**Comment by TagaSanPedroAko** [comment]
On the unnumbered Trans-Canada routes (all of those in Ontario and Quebec), those should be rendered with a Trans-Canada shield without number (i.e. the maple leaf). GMaps just does that. Apple adds a 1 however. Not sure with the paper ones (MapArt, CAA/AAA, Rand McNally, etc). 

Back on Alberta shields, for the "special trailblazers", in addition to the majority of the signs having elements under Crown copyright, most of those are of little use for navigation. Only usable so far is those for Queen Elizabeth II Highway (the "QE2") and Yellowhead, but the QE2 trailblazer is under Crown copyright. The Yellowhead design seems to be already out of copyright (and Apple Maps use it, the one used being those by BC), but not sure. That said, both the QE2 and Yellowhead are already added as names, and there's no separate route relations for them.

**Comment by TagaSanPedroAko** [comment]
In regard to the demos, it's like those I see in #193 #195 #217 #219

**Comment by 1ec5** [comment]
Oh, those are pull requests which contain screenshots of the changes in action. No one has implemented the Alberta shields yet, but you’re more than welcome to open a pull request. If you’re interested, please take a look at [this guide](https://github.com/ZeLonewolf/openstreetmap-americana/blob/a54a346044b36f8a6f3a5706d02bcf9952f0a500/style/CONTRIBUTE.md#highway-shield-contributors-guide).

**Comment by TagaSanPedroAko** [comment]
In regard to the shield for 1-216 series ("primary") highways, it'll be like those for #195. The same shield can be used also for Manitoba provincial trunk highways. For BC, it'll be rounded at the bottom.
