### ISSUE TITLE
Tennessee shields

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#303]
Tennessee has one "network" of state highways, though signage can shift between either of two shields depending on a segment's importance in the road hierarchy. Route numbers can have up to 3 digits.

Existing relations are tagged with `network=US:TN`, conflating both shields into one network. There has been some previous discussion towards new network values that correspond to shield appearance, but none so far have produced the change in tagging guidelines necessary for renderers to support Tennessee highway shields.

Primary shield:
![Tennessee_155](https://user-images.githubusercontent.com/1732117/165160421-13dc1eed-1b6d-4c96-8cac-eeac5f0c1b4f.svg)

Secondary shield:
![Secondary_Tennessee_171](https://user-images.githubusercontent.com/1732117/165160423-b5ccf78f-87e7-40b4-af8e-ecfa9ed10e88.svg)

**Comment by 1ec5** [comment]
> Existing relations are tagged with `network=US:TN`, conflating both shields into one network. There has been some previous discussion towards new network values that correspond to shield appearance, but none so far have produced the change in tagging guidelines necessary for renderers to support Tennessee highway shields.

I think [this wiki page](https://wiki.openstreetmap.org/wiki/Tag:network%3DUS:TN#Distinguishing_primary_and_secondary_routes) still describes the current and historical tagging situation accurately.

The `highway`-based approach isn’t necessarily incompatible with the [2021 highway classification guidelines](https://wiki.openstreetmap.org/wiki/United_States/2021_Highway_Classification_Guidance), but we would need a change to OpenMapTiles/Planetiler to expose `highway` in the `transportation_name` layer. Unfortunately, that approach is fragile because it would tie road classification to shields more tightly than in any other state except Puerto Rico, which incidentally has the same tagging conundrum: #240.

My experience working on #190 has softened me to a third approach of splitting out `US:TN:secondary` even though it would result in very fragmented route relations. At least it would be consistent with the approach taken in countries that rigorously signpost their freeways as a different kind of route than connecting non-freeways. We could perhaps relate `US:TN:primary` and `US:TN:secondary` routes into `US:TN` superrelations to preserve the ability to see the route as a whole.

**Comment by Pengor** [comment]
I agree using `highway=*` tags to determine shields sounds fragile due to the nature of highway classifications being somewhat fickle in the past (hopefully the ongoing highway reclassification processes will help stabilize that though). The "fragmented" routes with a superrelation idea sounds promising to me; mostly because it avoids the `highway` tag, but also if something similar is being used elsewhere it may be easier to adopt.

**Comment by zekefarwell** [comment]
I've been driving in Tennessee for the past few days and have seen both shields in use.  There doesn't seem to be much rhyme or reason to where one or the other is used, but I guess the triangles are theoretically on less important sections.  This seems like a similar situation to what we have in Vermont (described in #268) with sections of state numbered routes using a different shield where they are town maintained.  The current plan (already complete?) in VT is to split off these town maintained sections into separate route relations with`network=US:VT:Town` instead of the typical `network=US:VT`.  Seems like doing something similar in Tennessee would be appropriate with `network=US:TN` and `network=US:TN:Secondary`.  A data consumer that doesn't wish to display this distinction can match `network=US:VT*` and `network=US:TN*` to display a single shield for all routes in each network.  The fragmenting of route relations is unfortunate, but I can't see a better way to capture this nuance.

**Comment by claysmalley** [comment]
> A data consumer that doesn't wish to display this distinction can match `network=US:VT*` and `network=US:TN*` to display a single shield for all routes in each network.

Well, ideally, the tagging would be clearly defined and they wouldn't have to rely on wildcard matching. I like the guidelines you've presented with `network=US:TN` and `network=US:TN:Secondary`.

For version 1 I guess we could go forward with rendering `network=US:TN` and worry about the specifics of secondary highways later.

**Comment by ZeLonewolf** [comment]
I would not be opposed to putting the burden on a future Tennessee mapping community to adding more complexity to their route network tagging in order to achieve a more nuanced rendering.

**Comment by 1ec5** [comment]
The biggest problem currently is that the existing tagging conventions have been muddled by folks unaware of the existence of two separate networks. So any migration to a new tagging convention will require digging through feature histories across splits and merges or, more likely, taking a fresh look at the same TDOT source that NE2 used.

In the meantime, a binary classification that assumes primary unless known to be secondary won’t be as usable in Tennessee as it is with Vermont’s town highways, because the secondary route segments are far more numerous and lengthier than the primary route segments.

**Comment by 1ec5** [comment]
[Changeset 120,695,565](https://www.openstreetmap.org/changeset/120695565) refactors one state route into child route relations along three axes:

* Primary (`network=US:TN:primary`) versus secondary (`network=US:TN:secondary`)
* Signed (`ref`) versus unsigned (`unsigned_ref`)
* Northbound (`direction=north`) versus southbound (`direction=south`)

Not all state routes will need this level of complexity. Judging from [Wikipedia’s list](https://en.wikipedia.org/wiki/List_of_state_routes_in_Tennessee), 86 state routes are a mix of primary and secondary segments. However, most of them are wholly or partially unsigned; many unsigned segments have been excluded from route relations. The [separate relations per cardinal direction](https://wiki.openstreetmap.org/wiki/Route_directions) aren’t strictly necessary in a first pass.

**Comment by ZeLonewolf** [comment]
If someone is working on this and requires a map data update, please let me know.

**Comment by claysmalley** [comment]
Let's find at least one Tennessee state route with signed primary and secondary portions, and map it before we go through with a data update. As a side note, I've mapped a sampling of Texas county roads and I'd love to have them show up so I can work on their shields.

**Comment by zekefarwell** [comment]
Route 62 was one I drove on recently where I'm pretty sure I saw both shield types.

**Comment by ZeLonewolf** [comment]
@zekefarwell is currently conducting a field survey to confirm that variety of our highway signage is, in fact, insane.

**Comment by 1ec5** [comment]
[Changeset 120,738,589](https://www.openstreetmap.org/changeset/120738589) refactors SR&nbsp;394 into child relations for primary versus secondary segments (both signposted) and eastbound versus westbound.

[Changeset 120,734,828](https://www.openstreetmap.org/changeset/120734828) refactors SR&nbsp;283 into child relations for primary versus secondary segments (both signposted).

**Comment by zekefarwell** [comment]
Some references from the latest Tennessee highway map:
![PXL_20220509_233624554~2](https://user-images.githubusercontent.com/281482/167518174-da344dd4-25bc-4bb4-ade2-34da98574568.jpg)
![PXL_20220509_232852442~2](https://user-images.githubusercontent.com/281482/167518175-84297c2c-8a9a-4937-b73d-f3b1ef90a0a9.jpg)

**Comment by claysmalley** [comment]
@ZeLonewolf I think we're ready for that data update now.

**Comment by ZeLonewolf** [comment]
I should be able to do it this week.  I need three hours when I can babysit an AWS instance :-D

**Comment by 1ec5** [comment]
Here’s the full list of `network` values to render:

* `US:TN:primary`
* `US:TN:primary:Business`
* `US:TN:primary:Bypass`
* `US:TN:secondary`
* `US:TN:secondary:Alternate`
* `US:TN:secondary:Truck`

**Comment by zekefarwell** [comment]
Any particular reasoning for `primary` and `secondary` rather than `Primary` and `Secondary`?  I recommended `US:VT:Town` for Vermont because it seems like all the network values were meant to be proper cased.  Should we have done `US:VT:town` instead?

**Comment by 1ec5** [comment]
If I’m not mistaken, banner parts like `:Alternate` and `:Truck` were originally copied from [`modifier`](https://wiki.openstreetmap.org/wiki/Key:modifier), a freeform text key intended to match the case used in writing or on non-uppercased signs. The thinking went that you’d write “U.S. 50 Truck”, not “U.S. 50 truck”. This was one of NE2’s many innovations, another being [`HFCS=Urban Minor Arterial - Other`](https://wiki.openstreetmap.org/wiki/Key:HFCS).

Otherwise, the predominant practice globally uses snake_case for non-geographic, non-banner parts of `network`, just like for any non-freeform key. For example, Montana’s secondary state routes and Ontario’s secondary provincial routes are tagged `network=US:MT:secondary` and `network=CA:ON:secondary`, respectively. One benefit of using lowercase is that it’s possible to distinguish the geographic scope part of the value (`US:MT`) from the subtype (`secondary`) by case alone, since we already [made the mistake](https://wiki.openstreetmap.org/wiki/Talk:Key:cycle_network#What_additional_benefit_does_this_tag_provide%3F) of not using hyphens per ISO&nbsp;3166-2.

I noticed `US:VT:Town` and `US:WV:County` and didn’t think much of it. However, with @claysmalley’s [county route proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/County,_city_and_local_highway_networks_in_the_United_States) doubling down on underscores for county names, it seemed like the trend was moving away from NE2’s freeform text style. The lowercase form looks less exotic to me, but I admit having second thoughts as soon as I needed to append a banner like `:Alternate`, resulting in a mix of cases.

**Comment by zekefarwell** [comment]
Makes sense.  Seems like we're trying to use proper case only for actual proper names.  I guess my aiming for consitency was futile.  May as well leave the `US:VT:Town` value for now, since the tileset was just updated with it.  There are only 24 uses so it should be trivial to change to `US:VT:town` later if needed.  I suppose ideally the banner values would also be lowercase to fit the pattern, but that would be a much bigger effort to change at this point.

**Comment by 1ec5** [comment]
Tennessee’s truck state routes consistently use a non-MUTCD-compliant <img src="https://upload.wikimedia.org/wikipedia/commons/9/98/MUTCD_R14-1.svg" width="32" alt="Truck Route" align="top"> plaque instead of the usual <img src="https://upload.wikimedia.org/wikipedia/commons/8/8e/Truck_plate.svg" width="32" alt="Truck" align="top">. So there’s nothing consistent about what Tennessee is doing anyways. 😅
