### ISSUE TITLE
Label airports by FAA LID instead of IATA airport code

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#353]
As of #318, airports are labeled at low zoom levels by a three-letter IATA airport code or a four-letter ICAO airport code if there’s no IATA airport code. Americans are familiar with three-letter airport codes, but these are the [FAA location identifiers](https://en.wikipedia.org/wiki/Location_identifier#FAA_identifier) (LIDs), which overlap with IATA codes in many but not all cases. Should we prefer FAA LIDs over IATA airport codes where available?

Among the [primary airports in the U.S.](https://en.wikipedia.org/wiki/List_of_airports_in_the_United_States), 14 have differing IATA and FAA codes, including Saipan International Airport on Guam (`SPN` versus `GSN`). In some cases, the FAA and IATA use the same code for different airports in the U.S. For example, `BVU` is the IATA code for [Beluga Airport](https://en.wikipedia.org/wiki/Beluga_Airport) in Alaska but the FAA LID for [Boulder City Municipal Airport](https://en.wikipedia.org/wiki/Boulder_City_Municipal_Airport), a reliever for the Las Vegas International Airport.

[<img src="https://user-images.githubusercontent.com/1231218/171152229-05997dbb-c079-43f1-a187-5bd5c0474dda.png" width="400" alt="Beluga">](https://zelonewolf.github.io/openstreetmap-americana/#10/61.1721/-151.0423) [<img src="https://user-images.githubusercontent.com/1231218/171152472-edadbac8-fb27-4bb5-97bd-3d81118b9a8e.png" width="400" alt="Boulder City">](https://zelonewolf.github.io/openstreetmap-americana/#10.23/35.9493/-114.8595)

https://github.com/ZeLonewolf/openstreetmap-americana/blob/72afcba60ea71afdad701a7b68183bca76ad5563/style/layer/aeroway.js#L161

**Comment by wmisener** [comment]
I would've guessed that most Americans are most familiar with the IATA codes for their nearby airports, as I think that's what goes on the luggage tags. But maybe people especially interested in aviation (I don't know that much about the subject in detail) would prefer the FAA codes? Introducing this would also mean the project would treat US airports slightly differently than airports in other countries when rendering.

**Comment by 1ec5** [comment]
Oh, well I was mistaken then for thinking the FAA LIDs are what’s on the luggage tags. That would be a good argument in favor of the IATA codes as is. At least at these zoom levels, we seem to be targeting a general audience rather than pilots.

**Comment by wmisener** [comment]
For what it's worth, United Airlines's website uses Saipan's IATA code (SPN) rather than its FAA code (GSN). Similarly, American and Delta use the IATA code (MQT) for Sawyer International Airport, rather than its FAA code (SAW). So at least the airlines seem to favor the IATA codes.
<img width="598" alt="Screen Shot 2022-05-31 at 7 50 07 PM" src="https://user-images.githubusercontent.com/58491489/171319011-e12db6db-ab1c-4b2a-8260-143a19dea116.png">
<img width="695" alt="Screen Shot 2022-05-31 at 7 57 51 PM" src="https://user-images.githubusercontent.com/58491489/171319023-51bd3112-e3d2-437c-af26-5aa73fb1ea77.png">
<img width="390" alt="Screen Shot 2022-05-31 at 7 55 10 PM" src="https://user-images.githubusercontent.com/58491489/171319024-914211b3-74c4-436a-b109-691b5e17e370.png">

**Comment by 1ec5** [comment]
OK, you convinced me – IATA codes are the way to go. Thanks for the reality check!
