### ISSUE TITLE
Support nat_ref and reg_ref

### ISSUE THREAD

**Issue by riiga** [ZeLonewolf/openstreetmap-americana#364]
I suggest that `nat_ref` and `reg_ref` be supported in addition to the standard `ref`. The most developer-friendly would probably be as an option that can be set when specifying a route shield for a specific network.. The tags have around 100 000 uses on taginfo each.

Why I'm opening this issue is because this support is need to properly support rendering of the E-road network as well as (local to me) Swedish county routes.

The E-road network officially uses e.g. `E 04` as the ref, but in many countries, the leading zero is omitted and this is specified with `nat_ref=E 4` on the route relation. Another solution could be to leave out any leading zeroes.

County routes in Sweden are tagged with both `ref` and `reg_ref`, where the `ref` is a unique identifier consisting of the county letter and a number, while `reg_ref` is just the number and can be the same reference in another county. E.g [this road](https://www.openstreetmap.org/way/175642246) which has `ref=E 580` and `reg_ref=580`. Note also that the letter can be `E` which a ref-based renderer would take as being an E-road when it is not. This is thankfully avoided by relying on network tagging, but the shown number should still be `reg_ref`, not `ref`.

If any other countries make use of these or similar special ref tags, feel free to also add that to this discussion.

**Comment by zekefarwell** [comment]
We want to render shields with the same ref value shown real world shield signs, and this is the same as the value that should be in `ref` on the route relation.  If the signs have `E 580` then the route relation should have `ref=E 04` if the signs just have `580` then it should be `ref=580` and the `network` value is used to specify the proper shield design.  

I took a look at the [linked road](https://www.openstreetmap.org/way/175642246) on street view imagery and didn't see any shields at all, so it seems this case should probably be using `unsigned_ref` instead of `ref`.

**Comment by riiga** [comment]
I see your point. I'll rethink my approach to this and work with the OSM data.
