### ISSUE TITLE
Missing non-Latin and extended Latin script characters

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#393]
The typeface used for labels, Metropolis Bold, is missing many Latin letters with diacritics.

<img width="600" alt="Ảnh chụp Màn hình 2022-06-11 lúc 04 52 21" src="https://user-images.githubusercontent.com/1732117/173191707-b3b8b5fb-59d9-47a1-b343-116112bf9b3c.png">

Examples of missing letters in labels:

Chișinău, Moldova
![Screenshot from 2022-06-11 10-14-58](https://user-images.githubusercontent.com/1732117/173191587-be3b40e6-4739-4b85-90b7-2fa13dde69a1.png)

Bắc Giang and Hải Dương, Vietnam
![Screenshot from 2022-06-11 10-16-17](https://user-images.githubusercontent.com/1732117/173191588-8aab14c6-713a-47e5-af2b-fe44109f5e09.png)

**Comment by 1ec5** [comment]
It would be possible to produce font PBFs that composite Metropolis with a fallback font that covers more of Unicode’s Latin blocks. However, Metropolis is a relatively unique font, and I haven’t come across a fork of it that adds more character support.

This could be an opportunity to replace Metropolis with an altogether different font, bundle it with the Americana package, and deploy it over GitHub Pages. After all, if we’re aiming for a familiar road atlas aesthetic, then the typefaces are a big part of that. Road atlases have used many typefaces, but one as geometric as Metropolis is rare, because space economy is usually a consideration.

**Comment by ZeLonewolf** [comment]
Note there was no design choice on my part to use Metropolis, or was just one of the few I could figure out how to get working.

**Comment by claysmalley** [comment]
Non-Latin scripts confirmed to be missing:
* Cyrillic
* Greek
* Georgian
* Armenian
* Arabic
* Hebrew
* Cherokee
* Canadian Aboriginal Syllabics
* Tifinagh
* Ethiopic
* Devanagari
* Bengali
* Gurmukhi
* Gujarati
* Odia
* Tamil
* Telugu
* Kannada
* Malayalam
* Sinhala
* Thaana
* Tibetan
* Burmese
* Khmer
* Thai
* Lao
