### ISSUE TITLE
Duplicate badges

### ISSUE THREAD

**Issue by michaelblyons** [ZeLonewolf/openstreetmap-americana#423]
I do not know whether this is your job to fix or not, but the US-15 in Virginia has north and southbound routes mapped separately. They're both part of a super-route. Anyway, the badge shows up twice. 

<img width="328" alt="Screen Shot 2022-06-15 at 6 51 59 PM" src="https://user-images.githubusercontent.com/2701605/173955502-1ba6bde3-c8d2-4b28-8498-f46da773ace5.png">

**Comment by 1ec5** [comment]
For reference, [this way](https://www.openstreetmap.org/way/49850553) is a member of the [northbound](https://www.openstreetmap.org/relation/6930147) and [southbound U.S.&nbsp;15](https://www.openstreetmap.org/relation/6930146) route relations.

I can also reproduce this issue along [this way](https://www.openstreetmap.org/way/33266569) that’s a member of the [eastbound](https://www.openstreetmap.org/relation/13578987) and [westbound SR&nbsp;32](https://www.openstreetmap.org/relation/13578988) route relations in Ohio:

[<img src="https://user-images.githubusercontent.com/1231218/173956021-e1b70ad9-139b-423e-b84e-6bed47f187e6.png" width="400" alt="SR 32">](https://zelonewolf.github.io/openstreetmap-americana/#14.79/39.1227/-84.32637)

The problem lies in the vector tiles:

<img src="https://user-images.githubusercontent.com/1231218/173956302-5c0a6ab8-25a1-4b86-a0c1-5e1baaa2c88d.png" width="214" alt="inspect">

This would be fixed in openmaptiles/openmaptiles#1361.

**Comment by michaelblyons** [comment]
https://github.com/openmaptiles/openmaptiles/pull/1361 is merged now, but I don't know when the tiles become available.

**Comment by ZeLonewolf** [comment]
I'll build a full-zoom Ohio so we can test the behavior.

**Comment by ZeLonewolf** [comment]
We should probably decide how we want to administratively mark issues which are not resolved in the public demo but are fixed in the underlying software.  It'll probably be awhile before a new release of OMT and a subsequent update of planetiler.

**Comment by ZeLonewolf** [comment]
From omt-tools render of Ohio:

([localhost link](http://localhost:1776/#map=14/39.12268/-84.32453))
![image](https://user-images.githubusercontent.com/3254090/214943723-1145b83e-2fb0-4f69-9cd0-fd47c7d7eb7a.png)

([localhost link](http://localhost:1776/#map=12/39.31035/-82.96804))
![image](https://user-images.githubusercontent.com/3254090/214944002-a42f410a-5326-49d8-86ed-6e0ed8cae0a7.png)

**Comment by michaelblyons** [comment]
Maybe fixed? Can anyone confirm?

**Comment by 1ec5** [comment]
Yes, the same spot in https://github.com/ZeLonewolf/openstreetmap-americana/issues/423#issuecomment-1157036014 now shows only a single state route shield:

[<img src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/1231218/eb7cae82-2025-437a-b13c-432628f6517b" width="400" alt="SR 32">](https://zelonewolf.github.io/openstreetmap-americana/#map=14.79/39.1227/-84.32637)
