### ISSUE TITLE
Shields of Venezuela

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#424]
Venezuela también marca las carreteras con los escudos diferentes por red. [Esta página wiki](https://wiki.openstreetmap.org/wiki/ES:Venezuela/Listados/Nomenclatura_de_carreteras) lista el escudo y la relación de cada ruta.

Parece que las relaciones tienen todas las etiquetas necesarias, pero desafortunadamente los valores `ref` incluyen el prefijo de la red, mientras que los señales de hecho no muestran el prefijo. Generalmente este proyecto considera `ref` en una relación como el texto principal y literal para mostrar en el escudo.

****

Venezuela also marks its highways with shields that vary by system. [This wiki page](https://wiki.openstreetmap.org/wiki/ES:Venezuela/Listados/Nomenclatura_de_carreteras) lists the shield and relation for each route.

It looks like the relations have all the required tags; however, unfortunately the `ref` values contain a prefix corresponding to the network, whereas the actual signs omit the prefix. Generally this project considers `ref` on a relation to be literally the primary text on the shield.

**Comment by Wguayana** [comment]
Hola (sorry, I do not speak English) [soy un activo mapeador en Venezuela](https://www.openstreetmap.org/user/Wilmer%20Osario), y vengo en nombre de la comunidad de maperos de ese país. También he estado trabajando activamente en agregar nuestra _road network_ a OSM.

La clasificación de carreteras en Venezuela es sencilla, tenemos **tres niveles** de clasificación con símbolos diferentes:

![Venezuela road network 1](https://user-images.githubusercontent.com/51529917/174324588-9812c763-c594-4503-8552-1c9706acc574.jpg)

**1.** El primero es de carretera **Troncal** cuyo símbolo [es la forma de nuestro escudo nacional](https://en.wikipedia.org/wiki/File:Coat_of_arms_of_Venezuela.svg), es la red de carreteras más importante del país. En OSM lo identificamos con la etiqueta **ref=T-xx**
**2.** El segundo es de carretera **Local** cuyo símbolo es un simple círculo, es la red de carreteras regionales, y lo identificamos con la etiqueta **ref=L-xx**
**3.** El tercero es de carretera **Ramal** cuyo símbolo es un simple rombo, es la red de carreteras menores y menos importante, y lo identificamos con la etiqueta **ref=R-xx**

Además, **hay distinciones** entre [cada estado](https://en.wikipedia.org/wiki/States_of_Venezuela) del país. Cada uno de ellos tiene números propios de Locales y Ramales, por lo que no es raro ver que se repiten números por todo el país, los cuales identificamos con una abreviación:

![Venezuela road network 3](https://user-images.githubusercontent.com/51529917/174326891-18d466bf-78aa-40f8-9b84-e23c1176a0e5.jpg)

Por ejemplo la [**Local 3 de Zulia**](https://www.openstreetmap.org/relation/13193089) y la [**Local 3 de Bolívar**](https://www.openstreetmap.org/relation/13004756), que aunque sean carreteras diferentes, ambos tienen el mismo símbolo y el mismo número.

Con las Troncales la distinción es mínima y no es obligatoria, ya que los números no se repiten. Por ejemplo, la **Troncal 9** es única en todo el país, y aunque recorra [4 estados](https://en.wikipedia.org/wiki/States_of_Venezuela), siempre será la misma **T-9** para todos ellos. Pero para cuestiones prácticas de OSM decidimos hacerles etiquetas propias.

--------------------------------------------------------------------------------

También hay una pequeña variación de los símbolos. En cuanto a las Troncales y Locales, está **la variante completa** que es la mostrada en las señales de tránsito, y **la variante simple** que es la mostrada en mapas y demás cartografía:



![Venezuela road network 6](https://user-images.githubusercontent.com/51529917/174329226-5be480d1-c816-4f51-91df-7a05c930293a.jpg)

![Venezuela road network 7](https://user-images.githubusercontent.com/51529917/174329261-f64d259a-4da0-4f80-a095-34731646745f.jpg)

![Señal de Troncal 1 de Venezuela](https://user-images.githubusercontent.com/51529917/174329404-8494ecad-8221-471d-8e11-30076b3ebe13.jpg)

![Venezuela road network 8](https://user-images.githubusercontent.com/51529917/174329500-059a35b4-61a6-4b9b-948d-0cb0deeb518e.jpg)

![Venezuela road network 2](https://user-images.githubusercontent.com/51529917/174330049-0bae7e85-9882-470a-9240-3ed23e1bcd90.jpg)

![Venezuela road network 5](https://user-images.githubusercontent.com/51529917/174330165-e3ce4c65-3d6c-45d0-befb-aa3013de4c45.jpg)

![Venezuela road network 4](https://user-images.githubusercontent.com/51529917/174330191-a8e8ef59-3964-4329-9f94-7e61f742c445.jpg)

**Comment by Wguayana** [comment]
Actualmente aún nos falta por agregar 2 estados, y redactar toda la documentación referente al tema [en nuestra wiki](https://wiki.openstreetmap.org/wiki/ES:Venezuela/Listados/Nomenclatura_de_carreteras).

También me he tomado la libertad de digitalizar cada símbolo [y publicarlos en Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:Diagrams_of_route_signs_of_Venezuela).

**Comment by claysmalley** [comment]
(Lo siento, mi español es limitado. La mayor parte de esto está traducido automáticamente.)

Gracias por recopilar toda esta información. Estoy emocionado de tener escudos venezolanos en el mapa.

Este proyecto ya tiene el arte necesario para las carreteras locales y ramales, porque se han agregado escudos idénticos en otros lugares. Tendríamos que hacer nuevas ilustraciones para las carreteras troncales, lo cual no debería ser difícil.

Veo que los valores de `ref=*` en las relaciones `route=road` tienen como prefijo códigos de letras redundantes que no están presentes en los escudos. En este proyecto, usamos `network=*` para determinar qué escudo mostrar, y asumimos que el valor de `ref=*` se puede mostrar letra por letra en el escudo sin modificaciones (#141). El etiquetado de rutas en Brasil tiene un problema similar (#425), y aunque tenemos el arte listo para los escudos brasileños, los prefijos en `ref=*` nos impiden agregarlo al proyecto. A menos que se eliminen los prefijos de los valores `ref=*` en las rutas venezolanas, la implementación se bloqueará por la misma razón.

> Por ejemplo, la Troncal 9 es única en todo el país, y aunque recorra [4 estados](https://en.wikipedia.org/wiki/States_of_Venezuela), siempre será la misma T-9 para todos ellos. Pero para cuestiones prácticas de OSM decidimos hacerles etiquetas propias.

¿Podría describir las cuestiones prácticas por las que las troncales se dividen en muchos valores `network=*` que contienen códigos de estado de dos letras? Esto parece una complejidad innecesaria que podría simplificarse.

Por ejemplo, en EE. UU., el sistema de carreteras interestatales (`network=US:I`) tiene escudos con el nombre del estado (ejemplo en la parte inferior), aunque las carreteras están numeradas en un esquema nacional. Desde nuestra perspectiva, el nombre del estado es como una decoración y no es necesario para la identificación de la ruta, por lo que usamos solo un valor de `network=*` para las carreteras interestatales de todo el país. Sin embargo, para la conveniencia del mapeo, todavía dividimos las relaciones de autopistas interestatales donde cruzan las líneas estatales y agregamos `is_in:state=XX` (una etiqueta no procesada por este proyecto).

De paso, la Vía Panam se rastrea por separado aquí: #421

----

(Apologies, my Spanish is limited. Most of this is machine-translated.)

Thanks for compiling all this information. I'm excited to have Venezuelan shields on the map.

This project already has the necessary artwork for Locales and Ramales, because identical shields have been added elsewhere. We would need to add new artwork for Troncales, which shouldn't be hard.

I see that values of `ref=*` in `route=road` relations are prefixed with redundant letter codes not present on shields. In this project, we use `network=*` to determine which shield to display, and we assume that the value of `ref=*` can be displayed verbatim on the shield without modifications (#141). Route tagging in Brazil has a similar problem (#425), and even though we have the artwork ready for Brazilian shields, the prefixes in `ref=*` block us from adding it to the project. Unless the prefixes are removed from `ref=*` values in Venezuelan routes, implementation will be blocked for the same reason.

> For example, Troncal 9 is unique throughout the country, and even though it runs through [4 states](https://en.wikipedia.org/wiki/States_of_Venezuela), it will always be the same T-9 for all of them. But for practical OSM reasons we decided to make our own tags.

Could you describe the practical reasons Troncales are divided into many `network=*` values containing two-letter state codes? This seems like an unnecessary complexity that could be simplified.

For example, in the US, the Interstate Highway System (`network=US:I`) has shields bearing the name of the state (example at bottom), even though the highways are numbered on a national basis. From our perspective, the state name is like a decoration, and not necessary for route identification, so we use only one value of `network=*` for Interstate highways nationwide. However, for mapping convenience, we still divide Interstate highway relations where they cross state lines and add `is_in:state=XX` (a tag not processed by this project).

As a side note, the Pan-American Highway is tracked separately here: #421

<image src="https://user-images.githubusercontent.com/1732117/174456670-abd4108d-5150-4ab4-8092-e98e6cdd669f.svg" alt="I-80_(CA)" width="200" />

**Comment by Wguayana** [comment]
Lo siento, nos parece mala idea eliminar de OSM las relaciones de cada una de las Troncales divididas por estado, debido a que legalmente nuestras clasificaciones están segmentadas por estados. Por ejemplo, en el caso de las Troncales/Locales, legalmente los carteles en la carreteras deben mostrar el nombre del estado en el que se encuentran, como lo muestran documentos oficiales del ministerio de transporte:

![Venezuela road network 11](https://user-images.githubusercontent.com/51529917/176032726-27d2c128-a0d1-4c7e-a1db-390c9ec5e132.jpg)
![Venezuela road network 10](https://user-images.githubusercontent.com/51529917/176032803-ac92b960-c4ff-4862-89f0-8612678ebd58.jpg)

Por eso también son importantes nuestras etiquetas de `network=*`

![Venezuela road network 9](https://user-images.githubusercontent.com/51529917/176034536-f0313741-2956-49e3-bd47-2aa8db564af5.jpg)

--------------

También es mala idea eliminar los prefijos de la etiqueta `ref=*` en OSM, **por que son muy importantes para identificar el tipo de carretera en su forma básica sin escudos**, que de otra manera sería una gran confusión:

![Venezuela road network 12](https://user-images.githubusercontent.com/51529917/176034229-c179c3ab-4f06-41a7-808c-ea8d388118d5.jpg)

Hace unos 10 años cuando comenzamos a mapear nuestro país en OSM, intentamos hacer la clasificación sin los prefijos y no nos funcionó. Somos casi lo mismo que Brasil en este aspecto :(

**Comment by 1ec5** [comment]
> También es mala idea eliminar los prefijos de la etiqueta ref=* en OSM, por que son muy importantes para identificar el tipo de carretera en su forma básica sin escudos, que de otra manera sería una gran confusión:

Sí, en los EE.UU. tenemos la misma situación (y mucho más). Sin embargo, la etiqueta `ref` en las vías debe tener un prefijo, pero generalmente la misma etiqueta en las relaciones no tienen que tener un prefijo. Entonces las rutas estales estadounidenses tienen un prefijo en `ref` en las viás pero no en `ref` en las relaciones. Sólamente tiene un prefijo si es incluido en los señales o los nombres, como en Ecuador por ejemplo (#456).

No es necesario que repetir el prefjio en la relación porque esta información ya está indicado en la etiqueta `network`, que no ocurre en las vías. Sin un prefijo, los consumidores de datos pueden facilmente formatear el código según el contexto. Por ejemplo, puede incluir el prefijo en texto simple pero omitirlo en un ícono pequeño del escudo. Pero si el prefijo es incluido en `ref`, los consumidores de datos tienen que desarrollar las reglas para procesar el valor `ref` que varia por país o, en muchos casos, por provincia.

**Comment by 1ec5** [comment]
A propósito, gracias por las fotos de los señales troncales. Yo no sabía que los señales de rutas de Venezuela también indica el punto cardinal. He actualizado [la documentación](https://wiki.openstreetmap.org/wiki/Route_directions) sobre los dos maneras de indicar el punto cardinal de un sentido de la ruta en una relación.

**Comment by Wguayana** [comment]
En ese caso sí, podemos quitarle el prefijo a las relaciones de _routes_ y dejar las que están en las _ways_.

Entonces una de nuestras relaciones típicas, por ejemplo la [13003837](https://www.openstreetmap.org/relation/13003837), resultarían así:

- `type=route`
- `route=road`
- `network=VE:T:BO`
- `ref=19`
- `name=Troncal 19 de Bolívar`
- `source:ref=Ministerio de Transporte (2015)`

---------

Si está de acuerdo, puedo empezar a modificar las `ref` de todas nuestras relaciones de ruta para que cumplan con ese estándar, aunque tardaré varios días en conseguirlo.

**Comment by Wguayana** [comment]
La relación `route` de la **carretera panamericana** aún no la hemos definido, pero si la necesita rápido, puedo ponerme en ello.

**Comment by 1ec5** [comment]
> Si está de acuerdo, puedo empezar a modificar las `ref` de todas nuestras relaciones de ruta para que cumplan con ese estándar, aunque tardaré varios días en conseguirlo.

Muchísimas gracias @Wguayana, a mí su ejemplo parece bien. Si Ud. y la comunidad de mapeadores locales están seguro que quisieran continuar con los valores específicos de `network`, este proyecto puede adaptar por manera de listear todos los valores asociados con cada diseño de escudo. El formato de `ref` es la primera consideración. Después de que actualize unas relaciones, díganos y @ZeLonewolf refrescará las teselas vectoriales.

_Thank you @Wguayana, your example looks good to me. If you and the local mapping community are sure you’d like to keep using the specific `network` values, this project can adapt by listing out all the values associated with each shield design. The `ref` format is the main consideration. After you update some relations, let us know and @ZeLonewolf will refresh the vector tiles._

> En un contexto local, recorriendo el país nunca he visto que el gobierno hayan colocado esas señales de tránsito con el escudo de **panamericana** como se muestra en documentos oficiales, pero por todo el país hay muchas carreteras que llevan el nombre de "Carretera Panamericana", ya sea oficialmente o coloquialmente.

Sí, en varios casos es posible que es solamente un nombre de calle en vez de una parte de la ruta formalmente. Gracias por investigar la situación local.

Actualmente, para las redes de rutas numeradas, este representador automáticamente omite el escudo si la relación tiene una etiqueta `unsigned_ref` (significa “no señalizado”) en vez de `ref`. Una parte no señalizado de una ruta señalizado es representada por una “subrelación” con `unsigned_ref`. Sin embargo, para las redes nombradas que nunca tiene ninguna etiqueta `ref`, como la Carretera Panamericana, no sé cómo indicar que una parte de la ruta no es señalizada. 🤔

_Yes, in many cases it’s possible that it’s merely a street name rather than a formal part of the route. Thank you for looking into the local situation._

_Currently, for numbered route networks, this renderer automatically omits the shield if the relation has an `unsigned_ref` tag instead of `ref`. However, for named networks that never have any `ref` tag, such as the Pan-American Highway, I don’t know how to indicate that only one part of the route is unsigned. 🤔_

**Comment by Wguayana** [comment]
Ya terminé de arreglar todas nuestras relaciones 😄

Nuestras `network` son:

_Troncales:_

VE:T:SU
VE:T:MO
VE:T:DA
VE:T:BO
VE:T:AM
VE:T:GU
VE:T:AN
VE:T:CO
VE:T:PO
VE:T:AP
VE:T:BA
VE:T:ME
VE:T:ZU
VE:T:FA
VE:T:LA
VE:T:YA
VE:T:CA
VE:T:AR
VE:T:MI
VE:T:DC
VE:T:TA
VE:T:TR

_Locales:_

VE:L:NE
VE:L:SU
VE:L:MO
VE:L:DA
VE:L:BO
VE:L:AM
VE:L:GU
VE:L:AN
VE:L:CO
VE:L:PO
VE:L:AP
VE:L:BA
VE:L:ME
VE:L:ZU
VE:L:FA
VE:L:LA
VE:L:YA
VE:L:CA
VE:L:AR
VE:L:MI
VE:L:DC
VE:L:VA
VE:L:TA
VE:L:TR

_Ramales:_

VE:R:NE
VE:R:SU
VE:R:MO
VE:R:DA
VE:R:BO
VE:R:AM
VE:R:GU
VE:R:AN
VE:R:CO
VE:R:PO
VE:R:AP
VE:R:BA
VE:R:ME
VE:R:ZU
VE:R:FA
VE:R:LA
VE:R:YA
VE:R:CA
VE:R:AR
VE:R:MI
VE:R:DC
VE:R:VA
VE:R:TA
VE:R:TR

-------------------------

Aún nos faltan dos Estados por crear, cuyas etiquetas de `network` incluí en las listas de arriba.

**Comment by 1ec5** [comment]
¡Estupendo! Parece que también ha cambiado los valores `ref`, entonces ahora @ZeLonewolf puede regenerar las teselas vectoriales para finalizar #468.
