### ISSUE TITLE
Shields for remaining parkways of New York

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#516]
Parkways of Long Island have a black-on-white square shield with an illustration of a lighthouse in the middle, the name of the parkway on bottom, and an abbreviation of the name on top.

<img height="150" alt="Southern_Pkwy_Shield" src="https://user-images.githubusercontent.com/1732117/181241994-3d9a1f06-90a9-4e4d-aaca-18a1634af8bd.svg" />

The Lake Ontario State Parkway has a unique white-on-green roundel. The full name of the parkway is spelled out, with no accompanying abbreviation.

<img height="150" alt="Lake_Ontario_State_Pkwy_Shield" src="https://user-images.githubusercontent.com/1732117/181241996-6823f2b5-5529-4edc-abaa-fb97d5f3665a.svg" />

The Niagara Scenic Parkway has a shield similar to, but not quite the same as, parkways of the Hudson Valley (#515). Unlike other parkway shields, the capital letters are not enlarged. But it would be reasonable to assign the same shield style to this route.

<img height="150" alt="Niagara_Scenic_Pkwy_Shield" src="https://user-images.githubusercontent.com/1732117/181241998-fb4c3dfd-a048-44ce-8d66-2b30ba97d93c.svg" />

Currently, all of these routes are tagged with `network=US:NY`. A consistent tagging scheme will have to be devised and implemented before shield support can be added.

**Comment by quincylvania** [comment]
The Long Island parkways I [tagged as](https://www.openstreetmap.org/changeset/133539151) `network=US:NY:Parkway:LI`. This is consistent with the `network=US:NY:Parkway:NYC` tag used for that "subnetwork" of NY parkways.

The Niagara Scenic Parkway I [tagged with](https://www.openstreetmap.org/changeset/133538974) `network=US:NY:Parkway` since the signage is so similar to the Hudson Valley parkways.

The Lake Ontario State Parkway has been tagged as `ref=LOSP` since it was first mapped in 2010. This is nonstandard and looks kind of silly when rendered. However, since #799 we can key off the name if needed.
![Screenshot 2023-03-10 at 10 43 13 PM](https://user-images.githubusercontent.com/2046746/224463224-581db237-1f6c-47bd-91d3-190c540d456b.png)
![Screenshot 2023-03-10 at 10 42 16 PM](https://user-images.githubusercontent.com/2046746/224463225-2ed349e2-b75d-4286-b989-34c505359e0f.png)

**Comment by quincylvania** [comment]
> The Lake Ontario State Parkway has been tagged as ref=LOSP since it was first mapped in 2010. This is nonstandard and looks kind of silly when rendered.

In [133558122](https://www.openstreetmap.org/changeset/133558122) I moved the `ref` to `name:abbreviation` and tagged the route `network=US:NY:Parkway:LOSP` since no other NY parkway has signage like this.
