### ISSUE TITLE
Restrict rendering of boundary=protected_area depending on protect_class=*

### ISSUE THREAD

**Issue by tguen** [ZeLonewolf/openstreetmap-americana#551]
https://www.openstreetmap.org/relation/8274000

This area has `boundary=protected_area` and `protect_class=22`, [defined by the wiki](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area#Social-protected-area) as
> Cultural assets: protection of sites with special architecture or historic interest

e.g. `historic=district`. It doesn't make sense to render these areas like parks, and [it looks odd.](https://zelonewolf.github.io/openstreetmap-americana/#15/45.52625/-122.69262)

**Comment by wmisener** [comment]
I think this was [discussed on Slack](https://osmus.slack.com/archives/C01V02K52UX/p1626295139363500?thread_ts=1626282907.347800&cid=C01V02K52UX) way back when the rendering of protected areas was first adopted, and [has come up intermittently since](https://osmus.slack.com/archives/C01V02K52UX/p1654867845031749). I believe it was a conscious decision to render all `boundary=protected_area` the same, somewhat motivated by the opinion of some (myself included) that `boundary=protected_area`+`protect_class=22` is poor tagging for historic districts, which can just be tagged `historic=district` without any `protected_area` tags. In fact, while `protect_class=22` is tagged in the same way as IUCN codes and so may seem official, it was in fact entirely made up within OSM. So in a sense rendering these as parks provides mapper feedback.

**Comment by zekefarwell** [comment]
This style is also limited somewhat by the [OpenMapTiles](https://github.com/openmaptiles/openmaptiles) schema.   The schema doesn't include `protect_class` values so they aren't something we can filter on currently.

**Comment by ZeLonewolf** [comment]
Personally, I think it's a mistagging to tag a historic district like the one cited as a [protected area](https://en.wikipedia.org/wiki/Protected_area).  It isn't a protected area, and `historic=district` would be a completely appropriate tag for it. An example of an "area with historic interest" properly tagged as a protected area would be something like [Saratoga National Historical Park](https://en.wikipedia.org/wiki/Saratoga_National_Historical_Park).

I am open to hearing other opinions, but I'm of the opinion that the rendering is correct and the tagging is wrong.

**Comment by tguen** [comment]
Yes, it seems that NRHP features are not really "protected" and `protect_class=22` is not appropriate in this case. I've begun editing the features accordingly. I don't know of any case in which it is appropriate, so I can't really say how it should be rendered.

**Comment by ZeLonewolf** [comment]
Closing as unplanned based on discussion.
