### ISSUE TITLE
Render waterways and their labels

### ISSUE THREAD

**Issue by jleedev** [ZeLonewolf/openstreetmap-americana#58]
Motivation: Should be obvious, but of note — the river areas as simplified by openmaptiles have large gaps at low zoom levels and the linear rivers are needed to make this look right.

Desired qualities for the waterways (brainstorm harvested from slack):
- Serif font? We sure have a lot of sans fonts to choose from but no serifs. This is really a question for this style as a whole, but distinguishing "natural" features with a font choice seems to be a thing.
- Waterway labels appear at z12, which I'd consider fairly late. This might be a good boundary for rivers in general at the expense of not labeling large rivers.
- Some way to distinguish large and small rivers.
  - Depend on explicit width tagging? This exists almost nowhere.
  - Detect the river area with a spatial join? One can dream.
  - Join with wikidata to get the watershed area or discharge? Could work.
  - Absent any of these, the label needs to look good on a small river with no accompanying water area.
- A width heuristic — this is pretty much for small rivers. It can provide a nice transition for when the water area stops being mapped. If we assume that a typical river is 20 feet in width before we can expect the water area to have been mapped, then we can calculate that at z22 (at the equator) this should be 160 pixels in width, then ramp down by powers of two accordingly down to some minimum of (say) 2 or 4 pixels, then switch to a different ramp down to the minimum zoom.
  - Would it be possible for the style to multiply physically based widths by the cosine of the latitude?
- Curviness with regards to label placement. The default text-max-angle of 45° causes very few labels to appear on smaller streams and rivers except at very high zoom levels. This is actually somewhat convenient, the straightness of a river is a proxy for its size, so we get labels on only the biggest rivers for free.
  - Find a reasonable text-max-angle that results in more labels without being an unreadable mess.
  - Another approach: Add a separate layer with aggressively simplified waterways for the purpose of labeling?
- Generally speaking, make sure the labels look good embedded in a water area and against arbitrary non-water stuff.
- Could have stream labels offset running next to the waterway, and river labels running along the waterway, perhaps.
- Render waterway labels *under* bridges? Is this crazy pants or would it improve legibility.

**Comment by ZeLonewolf** [comment]
Below are a collection of samples of water renderings in paper maps in my collection.  Some things I note as an overall analysis:
* Water areas are almost universally rendered with a boundary, either blue or black.  In some cases that boundary is very subtle and in some cases more obvious.  This is a challenge to pull off nicely as @zekefarwell has discovered in some of his render sample work.
* There are attractive water area labels in serif, sans-serif, all-caps, and title case, with either blue or black text.
* There are no examples I was able to find of labels done with a "glow" effect -- all are simple font on a background.
* There are label examples that are italic, regular, and bold.

On thing that surprised me is that there is a trend of labeling rivers along the edge of the river area.  I think that is probably not technically achievable with our technology stack, but it is interesting.

There seems to be a trend of labeling large bodies of water in all-caps and lesser bodies of water in title case, but I'm not sure there's a good data-driven way to accomplish this.

I also note (see Philadelphia example), that when the features around a river get crowded, the cartographer simply moves the label to a free spot in the river.  In the example, the words "Delaware" and "River" are, comically, dozens of miles apart.  We will never see a paper map where a river label and a road conflict, because the cartographer can simply adjust the label to a position where they don't conflict.  So either we need to figure out how to make use of MapLibre's declutter capability or else decide which labels win on the over/under and live with the overlap.

Both Rand McNally, and the more recent AAA maps, all use title-cased, italic blue font for water labels and boundaries, so my vote is to use those elements of style.  They disagree on whether water labels should be in a serif or sans-serif font.   I personally think serif looks a little nicer, but I could be convinced either way, and maybe we could throw that distinction to a slack vote to see which one comes out nicer in practice.

The width and curviness stuff is way over my head, and I'm happy to defer to those that know more about it.

![2021-11-27 18 55 27](https://user-images.githubusercontent.com/3254090/143724232-17ece30d-e8e8-4506-8fbf-ba6d162d9bd8.jpg)
![2021-11-27 18 56 22](https://user-images.githubusercontent.com/3254090/143724233-0cf26721-b080-4451-9031-0dd65bf94f0f.jpg)
![2021-11-27 18 54 53](https://user-images.githubusercontent.com/3254090/143724231-1077c419-cb60-45cb-8ef5-8281ba10018a.jpg)
![2021-11-27 18 51 59](https://user-images.githubusercontent.com/3254090/143724227-54fa492c-ba91-47ef-8332-9f579eb478a4.jpg)
![2021-11-27 18 54 46](https://user-images.githubusercontent.com/3254090/143724230-8f79f294-85ff-4aa1-a8e9-786b57f2b6ef.jpg)
![2021-11-27 18 52 46](https://user-images.githubusercontent.com/3254090/143724228-b241dd16-24d9-4b78-bdeb-26afe6fe4542.jpg)
![2021-11-27 18 53 42](https://user-images.githubusercontent.com/3254090/143724229-bd53b893-2c53-4216-9f73-6379cc22fd41.jpg)

![2021-11-27 18 47 56](https://user-images.githubusercontent.com/3254090/143724226-a119120b-8d20-495d-a5e7-5ce98a65342f.jpg)

![2021-11-27 18 46 39](https://user-images.githubusercontent.com/3254090/143724225-02baab4f-0e50-47cd-8673-7bd5ce45c48f.jpg)
![2021-11-27 18 44 07](https://user-images.githubusercontent.com/3254090/143724221-ad20a95c-19e0-4e80-865b-577264bca70a.jpg)
![2021-11-27 18 44 43](https://user-images.githubusercontent.com/3254090/143724222-15308861-1ce1-4987-84d7-140aa68b8e06.jpg)
![2021-11-27 18 45 05](https://user-images.githubusercontent.com/3254090/143724223-22eced1a-102f-4560-99c9-0656b673d46e.jpg)
![2021-11-27 18 46 01](https://user-images.githubusercontent.com/3254090/143724224-1f7efac9-ccdf-4f37-b435-5647758f7177.jpg)

**Comment by 1ec5** [comment]
> In the example, the words "Delaware" and "River" are, comically, dozens of miles apart.

The generous spacing may not be purely for collision avoidance. The same effect is pervasive in USGS topographic maps: words are strategically placed so that there’s never any ambiguity as to which fork is which, but yet there’s no need to continuously label the stream and introduce more opportunities for collisions. I suspect some maps have employed a similar approach to road labeling.

For example, whether you’re following O’Bannon Creek as an orienteer or armchair mapper, you know you’ve gone down the wrong fork if you come across “Indiancamp” where you expected “Creek”. Note how the unnamed forks don’t cause the rest of the creek’s name to be labeled.

![obannon-indiancamp](https://user-images.githubusercontent.com/1231218/143725058-e5943f4a-e751-40d5-8f75-171a6677f6f5.png)

The downside to this approach is that it requires a bit more browsing to discover the full name of a stream. It may not be as good a tradeoff on an interactive map where additional labels can come in and out as the user zooms.
