### ISSUE TITLE
OpenHistoricalMap font stack doesn't support comma-separated lists

### ISSUE THREAD

**Issue by claysmalley** [ZeLonewolf/openstreetmap-americana#612]
#584 switched the font stack to the one used by OpenHistoricalMap. This includes a Frankenfont called OpenHistorical, which combines Open Sans and Unifont. While this font technically covers all scripts, Unifont is a last resort font and we should look for better solutions for scripts that currently show up in it. To do this, we need to have the ability to specify a comma-separated list of fonts so that glyphs can be loaded from the first font where they're available.

Unfortunately, the OpenHistoricalMap font stack is just a Git repository, not an API. In other words, we can't hit `https://openhistoricalmap.github.io/map-styles/fonts/Noto Sans Regular,Noto Sans Arabic Regular,Noto Sans Hebrew Regular,Unifont/0-255.pbf` and load four fonts. To display all languages attractively, we need a font stack that truly functions as an API.

Examples of Unifont:

- Georgian
![image](https://user-images.githubusercontent.com/3254090/204155027-0199a929-acc1-4129-a914-c9d69a5751b6.png)

- Armenian
![image](https://user-images.githubusercontent.com/3254090/204155118-987d3787-74b4-406b-aa3c-57cb41dd6984.png)

- Tamil
![image](https://user-images.githubusercontent.com/3254090/204155834-997d8750-e377-4ad4-ac36-92d50a50aaa0.png)

- Thai
![image](https://user-images.githubusercontent.com/3254090/204156147-fc1d51a9-b6bb-4bba-ad4b-2dd7aacde349.png)

**Comment by 1ec5** [comment]
I think the use of OpenHistorical was intended to be a stopgap measure. If we generate our own font “stack” specifically for the Americana style, then we can bake all the fallbacks inside that fontstack without having to specify them on the client side.

**Comment by ZeLonewolf** [comment]
#584 was really a stopgap.  Ideally I think we should create a separate fonts repo that can make a comprehensive font stack that can be used for vector tile applications.

**Comment by 1ec5** [comment]
Once we set up our own fontstack, we’ll want to choose something more sophisticated than Open Sans and Unifont. They don’t look all that great in Latin script, let alone other scripts. Some scripts like Arabic are probably illegible. The more modern [Noto](https://fonts.google.com/noto) project is a popular choice for projects that need multilingual support, including openstreetmap-carto.

With Noto, [some assembly is required](https://fonts.google.com/noto/use#how-are-noto-fonts-organized). They don’t vend a single pan-Unicode font because there isn’t necessarily a canonical way of writing the glyphs in a given script. The most obvious example is Han characters: #613. Another reason is that styles like “bold” and “italic” have no equivalent in many non-Latin scripts; there are other distinctions instead. They leave it up to designers to combine the individual scripts’ fonts as the design requires. Americana has an opportunity to pick a font for each script that conveys this style’s intended look and feel.

Ideally, we’d use a different fontstack when the user prefers Japanese labels than when they prefer Chinese, and a different fontstack when the user prefers Arabic than when they prefer Urdu. Since we try to show labels in the user’s preferred language, we can make assumptions that a local-language-only map such as openstreetmap-carto cannot: gravitystorm/openstreetmap-carto#4547. Even so, we will still need a pan-Unicode font for the local city name glosses added in #592.
