### ISSUE TITLE
Shield labels don't fit properly with Safari

### ISSUE THREAD

**Issue by bryceco** [ZeLonewolf/openstreetmap-americana#625]
Labels don't look correct when using Safari on iPhone and Mac.

See https://osmus.slack.com/archives/C01V02K52UX/p1647394819815939

![IMG_1994](https://user-images.githubusercontent.com/279734/208786039-c9e01630-db49-4605-beae-2803b37a4b2a.jpeg)

**Comment by quincylvania** [comment]
I spent some time investigating this. Here's the same area in Firefox:

<img width="600" alt="Screenshot 2023-01-29 at 3 22 14 PM" src="https://user-images.githubusercontent.com/2046746/215353804-d7bd146d-dd45-468d-b50e-faf8d15280bc.png">

Safari:

<img width="594" alt="Screenshot 2023-01-29 at 3 21 54 PM" src="https://user-images.githubusercontent.com/2046746/215353820-917bb2b4-d23d-4901-bdd4-83004b8f4759.png">

Not only is the vertical alignment off, but for some routes the font size is too small and the three-digit shields are used for two-digit routes.

The culprit seems to be that `measureText(text).actualBoundingBoxDescent` returns different values on Safari vs. other browsers.

https://github.com/ZeLonewolf/openstreetmap-americana/blob/584edc70f0874f970c26879e62a7830bb730ce7b/src/js/shield_text.js#L92-L95

Here are the metrics object for the `30` shield on Firefox:

```
actualBoundingBoxAscent: -0.9749999999999996
actualBoundingBoxDescent: 9.746484375
actualBoundingBoxLeft: 6.0975260734558105
actualBoundingBoxRight: 5.992187468210856
width: 10.933333396911621
```

Safari (returns more properties):

```
actualBoundingBoxAscent: -2
actualBoundingBoxDescent: 12
actualBoundingBoxLeft: 5.47265625
actualBoundingBoxRight: 5.47265625
alphabeticBaseline: -11
emHeightAscent: 0
emHeightDescent: 14
fontBoundingBoxAscent: 0
fontBoundingBoxDescent: 14
hangingBaseline: 0
ideographicBaseline: -14
width: 10.9453125
```

I tried various methods to get consistent values, without success. The path forward might be to re-implement the functionality without relying on `measureText` for the text height.

**Comment by ZeLonewolf** [comment]
Can someone with Safari confirm whether this is still an issue after all the recent work done with web fonts?

**Comment by cboone** [comment]
I'd say the vertical spacing is fixed, but the shield problem is not:

<img width="868" alt="Screenshot 2023-12-15 at 9 54 19 AM" src="https://github.com/ZeLonewolf/openstreetmap-americana/assets/99961/963667a6-5c55-48c9-a6b7-43d3be5d2c5a">

Link to that spot for future comparisons: https://zelonewolf.github.io/openstreetmap-americana/#map=10.6/40.046/-75.621
