### ISSUE TITLE
Remove Bulgaria motorway shield

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/openstreetmap-americana#650]
This style currently includes a green shield for `network=bg:national` under the assumption that every route in this network is a motorway or expressway (A-roads). In fact, this `network` tag is primarily being used for Republic Roads (I-roads), which should be marked by blue shields. The motorways and expressways form a separate network that should have a separate `network` tag. We should remove this incorrectly implemented shield, so that the local community can come to a consensus about a less ambiguous tagging scheme without undue influence from this style.

/ref #142

**Comment by ZeLonewolf** [comment]
Didn't mean to link the Nebraska issue.

I concur with the proposed change, we should probably remove that network from rendering rather than rendering half of Bulgaria's roads with the wrong symbol.

Perhaps @Dimitar5555 could help to sort out the network tagging of the two types of roads with the local community there.

**Comment by Dimitar5555** [comment]
We've resolved it back in November, I've forgotten to update the tags. Currently we have `network=bg:motorway` for motorways (current green shields), `network=bg:national` for republican routes (blue shields) and `network=bg:municipal` for municipal roads (which don't have shields or I've never seen one).
