### ISSUE TITLE
Legend displays intermittent lake or pond with gray fill instead of light blue

### ISSUE THREAD

**Issue by zekefarwell** [ZeLonewolf/openstreetmap-americana#664]
Maybe because the intermittent fill uses a semi-transparent color value?

<img width="635" alt="Screen Shot 2023-01-03 at 8 13 04 PM" src="https://user-images.githubusercontent.com/281482/210466772-90dbff13-cd9f-46c4-a933-d6343855e2c4.png">

https://zelonewolf.github.io/openstreetmap-americana/#map=16.84/-28.073345/153.423839

**Comment by 1ec5** [comment]
This might be due to some tweak I made after opening #632 or it might be related to #637. The screenshots in https://github.com/ZeLonewolf/openstreetmap-americana/pull/632#issue-1508522303 show that it worked at the time I opened the PR.

**Comment by 1ec5** [comment]
The cause seems to be the `waterIntermittentFill` constant added in #637:

https://github.com/ZeLonewolf/openstreetmap-americana/blob/321e7f69625299aea0d31e79ba89a466ae8845d6/src/constants/color.js#L6

The feature querying result comes back with an evaluated color object where each component is premultiplied by the opacity. The legend code produces `rgba(58.199999999999996, 64.8, 72, 0.3)` instead of `rgba(194, 216, 240, 0.3)`.
