### ISSUE TITLE
Pre-generate style.json

### ISSUE THREAD

**Issue by boldtrn** [ZeLonewolf/openstreetmap-americana#68]
Thanks for your great work creating this style. I was wondering if it would be possible to create a style.json from the style? As I understand there are currently multiple .js files that can be used in combination with Maplibre-GL to render a style.

I would like to use the style in combination with for example https://github.com/maptiler/tileserver-gl 

This is (as far as I am aware) only possible with a style.json.

So I was thinking, since all the rules are available as js files, wouldn't it be possible to generate a style.json from this?

**Comment by ZeLonewolf** [comment]
Yes, it is possible to generate a style.json.  In the following location, the americanaLayers object contains all the style, and you could use JSON.stringify() to turn it into a standalone JSON object.  We are planning to create a generated JSON version of the style for deployment so that each client doesn't have to generate the style each time.

https://github.com/ZeLonewolf/openstreetmap-americana/blob/f8d9f16076de2a30f8f88090d780afe56d205142/style/americana.js#L178

However, there is a big update to add concurrent highway shields that's in the works.  That update will depend on the `styleimagemissing` hook to generate highway shields, rather than the icon-based version that is currently in the map (which only supports single shields).  So, you'd still need to hook into javascript to do shield generation even with a separate style.json.  The concurrent shield work in progress can be found here:

https://github.com/ZeLonewolf/openstreetmap-americana/tree/openmaptilers-new-features-test

**Comment by boldtrn** [comment]
Thanks a lot, I wasn't aware of the shield issue, so I will wait a bit before actually trying to host the style on my server :)

**Comment by ZeLonewolf** [comment]
For the purpose of development, the desired behavior is:
1. A style JSON (we'll call it americana.json) is generated at compile time and posted to gh-pages where it is used in favor of the currently dynamically generated object.
2. Code for generating the style is located in separate folders from the code needed for style runtime (i.e. for shield loading)
3. Documentation is added that's sufficient for a style user to host their own copy, including shields.  The Americana runtime would include compiled sprites, the style JSON, and a javascript library for dynamic shield generation.
