### ISSUE TITLE
Improve relative highway classification prominence at z13+

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/openstreetmap-americana#84]
#62 provided an initial implementation of the road system through tertiary, and #82 provided an initial implementation of expressway rendering.    The high-zoom road network needs to be holistically considered to ensure that it's appropriately conveying relative prominence at these zoom levels.

Additional refinement is needed to ensure that:

1. More prominent roads are rendered more prominently.  Currently, the progressive switch from stroked to cased roads has the side effect of making the cased roads look less important that the thick stroked roads.  For example:

![image](https://user-images.githubusercontent.com/3254090/150269078-d4e86565-0f95-4368-b8a0-b75d5672b409.png)

2. Expressways are visually understood to be more prominent than non-expressway versions of the same highway class.

![image](https://user-images.githubusercontent.com/3254090/150269414-4465fc75-e9aa-4e25-937c-94f7ec736e36.png)

3. Expressway styling is not confused with tunnel rendering.  For example:

![image](https://user-images.githubusercontent.com/3254090/150269285-1a26cf68-405e-4077-8df4-213fae450c4e.png)

**Comment by adamfranco** [comment]
Currently `primary` switches from black stroke to cased-style at z14 and all lower classes at z16.

Currently the [fully-stroked look at z13](https://zelonewolf.github.io/openstreetmap-americana/?omss=highway-attributes&omsv=13#13/0/0) makes relative importance intelligible based on width:
![z13](https://user-images.githubusercontent.com/25242/154567774-6c132ce9-136c-45ac-aa07-ca6cc73c8d25.png)

Similarly, the [fully-case/filled look at z16](https://zelonewolf.github.io/openstreetmap-americana/?omss=highway-attributes&omsv=16#16/0/0) makes relative importance understandable.
![z16](https://user-images.githubusercontent.com/25242/154568064-a68e42e0-eb11-4998-b827-ce9158f4e25a.png)

The problem is in between those levels where there are mixed styles like [z15](https://zelonewolf.github.io/openstreetmap-americana/?omss=highway-attributes&omsv=15#15/0/0):
![z15](https://user-images.githubusercontent.com/25242/154568231-e4f6d5cb-4d9a-4802-9796-b230ded0d402.png)

**Shall we switch all lower classes to cased/fill-style at the same zoom?** Doing so would use width to maintain the relative prominence without struggling with the different visual weight between heavy black and light cased/fill styles.

It might be reasonable to make this switch a level above or below (somewhere in the z13-z15 range).
