### ISSUE TITLE
South Dakota State Bannered Route Shields

### ISSUE THREAD

**Issue by the-spui-ninja** [ZeLonewolf/openstreetmap-americana#969]
Hello all, there are bannered business and truck routes for the SD state highways (SD 50 Business in Vermillion and SD 52 Truck in Yankton). Currently these are under the US:SD network (https://wiki.openstreetmap.org/wiki/South_Dakota/State_Highway_Relations), I can break them out into US:SD:Business and US:SD:Truck for this. These would be displayed similarly to other bannered state routes.

**Comment by claysmalley** [comment]
> Currently these are under the US:SD network (https://wiki.openstreetmap.org/wiki/South_Dakota/State_Highway_Relations), I can break them out into US:SD:Business and US:SD:Truck for this.

Indeed, they would need to have separate `network` values in order to be rendered differently from a regular state route. It looks like the truck routes are tagged `US:SD:Truck` accordingly, but the business route is still tagged `US:SD`. Until this is changed, two State Highway 50s will appear together in Vermillion ([location](https://zelonewolf.github.io/openstreetmap-americana/#map=12.4/42.78557/-96.94435)):

![image](https://github.com/ZeLonewolf/openstreetmap-americana/assets/1732117/e0099199-cdfb-4cd2-8e4b-025e95c36b51)

**Comment by the-spui-ninja** [comment]
That should have just been updated.

**Comment by claysmalley** [comment]
Looks good. Sadly, the Americana build is currently broken, so tiles haven't been updated since yesterday. It might take a day or longer for the map to update, but that shouldn't be a blocker to implementing this.

**Comment by ZeLonewolf** [comment]
I've fixed the build issue (hopefully), it was a disk full issue.
